services:
    LogicBundle\EventListener\ProcesoListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
    comforce.cambio_a_dolares:
        class: AdminBundle\Twig\CambioADolares
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }        