<?php

namespace LogicBundle\Repository;

/**
 * ProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
